spring.application.name=container-inspection-api


server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/predictions_db
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Required for JSONB columns
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB


app.upload.dir=/Users/name/Documents/ai-container-inspection-platform/model_microservice/app/images/


python.service.url=http://localhost:5000/api/v1