




server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
python.service.url=${FASTAPI_URL}

app.upload.dir=${UPLOAD_DIR:/app/shared/images/}

